name: Integration Test

on: [push, pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: carms84/noetic_ros2
    steps:
      - name: Install dependencies
        shell: bash
        run: |
          apt update
          apt install -y python3-rosdep ros-noetic-audio-common-msgs
          rosdep init || true
          rosdep update

      - name: Set up workspace
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws/src
          git clone https://github.com/waleedelfieky/CogArch-SAR-TIAGo.git
          cd ~/catkin_ws
          catkin_make
          source devel/setup.bash

      - name: Run integration test
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          source ~/catkin_ws/devel/setup.bash
          rostest tiago_sar_cogarch integration_test.test
